server:
  applicationConnectors:
    - type: http
      port: 8095
  adminConnectors:
    - type: http
      port: 8096

#Config to MySQL database
database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: vikas@93
  url: jdbc:mysql://127.0.0.1:3306/dropwizard?useUnicode=yes&characterEncoding=UTF-8
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  checkConnectionOnBorrow: true
  evictionInterval: 10s
  minIdleTime: 1 minute

logging:
 level: INFO
 loggers:
   com.qonectcoin: DEBUG
   org.hibernate.SQL: DEBUG
   org.hibernate.type.descriptor.sql.BasicBinder: TRACE
 appenders:
   - type: console
     timeZone: JST